name: Update Coverage State

on:
  push:
    branches:
      - main
      - master
      - 'release/**'

permissions:
  contents: write

jobs:
  test-backend:
    uses: ./.github/workflows/test-backend.yml

  test-frontend:
    uses: ./.github/workflows/test-frontend.yml

  update-state:
    runs-on: ubuntu-latest
    needs: [test-backend, test-frontend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.email "github-actions@users.noreply.github.com"
          git config --global user.name "github-actions"

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Load existing state.json
        run: |
          git fetch origin ci-state || echo "No state branch yet"
          if git show origin/ci-state:state.json > /dev/null 2>&1; then
            git checkout -b ci-state origin/ci-state
          else
            git checkout -b ci-state
            echo "{}" > state.json
          fi

      - name: Debug coverage outputs
        run: |
          echo "Backend consoleApp: ${{ needs.test-backend.outputs.console-app-coverage-percent }}"
          echo "Backend services: ${{ needs.test-backend.outputs.services-coverage-percent }}"
          echo "Frontend: ${{ needs.test-frontend.outputs.frontend-coverage-percent }}"

      - name: Save current coverage to state.json
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          CONSOLE="${{ needs.test-backend.outputs.console-app-coverage-percent }}"
          SERVICES="${{ needs.test-backend.outputs.services-coverage-percent }}"
          FRONTEND="${{ needs.test-frontend.outputs.frontend-coverage-percent }}"
          LAST_RUN="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

          jq --arg branch "$BRANCH_NAME" \
            --arg console "$CONSOLE" \
            --arg services "$SERVICES" \
            --arg frontend "$FRONTEND" \
            --arg lastRun "$LAST_RUN" \
            '
            .[$branch] = {
              consoleApp: $console,
              services: $services,
              frontend: $frontend,
              lastRun: $lastRun
            }
            ' state.json > new_state.json && mv new_state.json state.json

          cat state.json

      - name: Commit and push updated state.json
        run: |
          git add state.json
          git commit -m "Update state for $GITHUB_REF on ${{ github.run_id }}" || echo "No changes"
          git push origin ci-state
