name: Create Pre-Release

on:
  workflow_dispatch:

jobs:

  gitversion:
    uses: ./.github/workflows/gitversion-job.yml

  build:
    uses: ./.github/workflows/build.yml
    needs: gitversion
    with:
      version: ${{needs.gitversion.outputs.semver}}

  # TODO would be good to valdate that the version that comes out of gitversion is in fact a pre-release labeled version. then copy this file and make a normal release that will take the non-labeled version in order to effectively bump the release.
  release:
    runs-on: ubuntu-latest
    needs: [gitversion, build]
    permissions: # Add permissions block here
      contents: write # Give the job write permission to create releases
    steps:

    - name: Download All Artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Echo
      run: |
        echo "THER VERSION: ${{needs.gitversion.outputs.semver}}"
        echo "Just Testing 1 ${{needs.gitversion.outputs.semver}}" > just-testing-1.txt
        echo "Just Testing 2 ${{needs.gitversion.outputs.semver}}" > just-testing-2.txt

    - name: Create Release
      if: ${{ !env.ACT }}
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{needs.gitversion.outputs.semver}}
        prerelease: true
        files: artifacts/**/just-testing*.txt
