# Run with `act --artifact-server-path ./artifacts -j publish`

name: Release

on:
  # Build can be run manually
  workflow_dispatch:
  push:
    # branches: [main]
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-**'

jobs:

  gitversion:
    uses: ./.github/workflows/gitversion-job.yml

  just-testing:
    runs-on: ubuntu-latest
    needs: gitversion
    permissions: # Add permissions block here
      contents: write # Give the job write permission to create releases
    steps:
    - name: Echo
      run: |
        echo "THER VERSION: ${{needs.gitversion.outputs.semver}}"
        echo "Just Testing 1 ${{needs.gitversion.outputs.semver}}" > just-testing-1.txt
        echo "Just Testing 2 ${{needs.gitversion.outputs.semver}}" > just-testing-2.txt

    - name: Create Release
      if: ${{ !env.ACT }}
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{needs.gitversion.outputs.semver}}
        files: just-testing*.txt
