name: Release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Choose whether to build a "Pre-Release" version or an official "Release".'
        required: true
        default: 'Pre-Release'
        type: choice
        options:
        - Pre-Release
        - Release

jobs:

  gitversion:
    uses: ./.github/workflows/gitversion.yml
    with:
      validatePreRelease: ${{ inputs.releaseType == 'Pre-Release' }}

  test:
    uses: ./.github/workflows/test.yml

  build:
    uses: ./.github/workflows/build.yml
    needs: [gitversion, test]
    with:
      # When "Release" is chosen, the pre-release tag will be stripped from the version in order to effectively bump to the upcoming release version.
      version: ${{ inputs.releaseType == 'Release' && needs.gitversion.outputs.majorMinorPatch || needs.gitversion.outputs.semVer }}

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions: # Add permissions block here
      contents: write # Give the job write permission to create releases
    steps:

    - name: Download All Artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Echo Some Pretend Build Files
      run: |
        echo "THER VERSION: ${{needs.build.outputs.version}}"
        mkdir -p artifacts/somebuild
        mkdir -p artifacts/anotherbuild
        echo "Just Testing 1 ${{needs.build.outputs.version}}" > artifacts/somebuild/just-testing-1.txt
        echo "Just Testing 2 ${{needs.build.outputs.version}}" > artifacts/anotherbuild/just-testing-2.txt

    - name: Create Release
      if: ${{ !env.ACT }}
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{needs.build.outputs.version}}
        prerelease: ${{ inputs.releaseType == 'Pre-Release' }}
        files: artifacts/**/just-testing*.txt
