# would be nice to ensure we don't try to add the tag again if it already exists on the same commit.  It should fail if it already exists on another commit.
name: Tag Pre-release

on:
  workflow_dispatch:

# Allow pushing tags
permissions:
  contents: write

jobs:
  gitversion:
    uses: ./.github/workflows/gitversion-job.yml

  tag:
    needs: gitversion
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate and tag
        env:
          SEMVER: ${{ needs.gitversion.outputs.semVer }}
          PRERELEASE_LABEL: ${{ needs.gitversion.outputs.preReleaseLabel }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "SemVer: $SEMVER"
          echo "Pre-release label: $PRERELEASE_LABEL"
          if [ -z "$PRERELEASE_LABEL" ]; then
            echo "Error: Missing pre-release label. Aborting."
            exit 1
          fi

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag -a "$SEMVER" -m "Version $SEMVER"
          git push origin "refs/tags/$SEMVER"
